repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: debug-statements
- repo: local
  hooks:
  - id: pyright
    name: pyright
    entry: uvx pyright@latest
    language: system
    pass_filenames: false
    types_or: [python, pyi]
  - id: ruff
    name: ruff
    entry: uvx ruff@latest check --force-exclude
    language: system
    types_or: [python, pyi]
  - id: ruff-format
    name: ruff format
    entry: uvx ruff@latest format --force-exclude
    language: system
    types_or: [python, pyi]
